services:
  _defaults:
    public: true
  
  #Exemple pour ajouter un service en mode public dans l'environnement de TEST uniquement:
  #test.TokenCookieService: '@App\Service\Authentication\Tokens\TokenCookieService'