name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  phpunit:
    runs-on: ubuntu-20.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - run: vendor/bin/phpunit