name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  phpunit:
    runs-on: ubuntu-20.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: 8.1

      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: '10.6.5' # Optional, default value is "latest". The version of the MariaDB
          #mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
          mysql root password:  #{{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
          #mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          #mysql password: '' #Required if "mysql user" exists. The password for the "mysql user"

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      
      - name: Setup test database
        run: php bin/console doctrine:database:create --env=TEST && php bin/console d:m:m --env=TEST

      - run: vendor/bin/phpunit