name: CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ubuntu-20.04

    services:
      mariadb:
        image: mariadb:10.6.5
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: wallstit_test
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Wait for MariaDB service to start
        run: sleep 5

      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Cloning main repository
        uses: actions/checkout@v3

      - name: Installing composer with PHP 8.1 version
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
      
      - name: Setup test database
        env:
          DATABASE_URL: mysql://root:rootpassword@127.0.0.1:3307/wallstit_test?serverVersion=10.6.5-MariaDB&charset=utf8mb4
        run: php bin/console doctrine:schema:update --env=TEST --force --no-interaction --complete

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Prevent PR merge on test failure
        if: ${{ failure() }}
        run: |
          echo "Tests failed. This PR cannot be merged." >&2
          exit 1