name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  phpunit:
    runs-on: ubuntu-20.04

    services:
      mariadb:
        image: mariadb:10.6.5
        ports:
          - 3307
        env:
          MYSQL_DATABASE: wallstit_test
          MYSQL_ROOT_PASSWORD: 
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      #- name: Setup PHP
      #  uses: shivammathur/setup-php@v2
      #  with:
      #    php-version: 8.1

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3307] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done          

      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: 8.1

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      
      - name: Setup test database
        run: php bin/console d:m:m

      - run: vendor/bin/phpunit