name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  phpunit:
    runs-on: ubuntu-20.04


    steps:
      - uses: ankane/setup-mariadb@v1
        with:
          mariadb-version: "10.6"
      #- name: Setup PHP
      #  uses: shivammathur/setup-php@v2
      #  with:
      #    php-version: 8.1
        
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: 8.1

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      
      - name: Setup test database
        run: php bin/console d:m:m

      - run: vendor/bin/phpunit